<template>
  <div class="modal fade" id="note-editor" tabindex="-1" role="dialog" aria-labelledby="note-editor-label">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="note-editor-label">New Note</h4>
        </div>
        <div class="modal-body">
          <form>
            <div id="note-editor__title-holder" class="form-group">
              <label for="note-editor__title">Title:</label>
              <input type="text" class="form-control" id="note-editor__title" v-model="title">
              <span id="note-editor__title-message" class="help-block hide">This field is required.</span>
            </div>
            <div id="note-editor__content-holder" class="form-group">
              <label for="note-editor__content">Content:</label>
              <textarea class="form-control" id="note-editor__content" v-model="content"></textarea>
              <span id="note-editor__content-message" class="help-block hide">This field is required.</span>
            </div>
            <div id="note-editor__category-holder" class="form-group">
              <label for="note-editor__category">Category:</label>
              <br>
              <select data-width="100%" class="selectpicker" id="note-editor__category" v-model="selectedCategory">
                <option value="uncategorized">Uncategorized</option>
                <option v-for="category in categories" :value="category">{{ category.name }}</option>
              </select>
              <span id="note-editor__category-message" class="help-block hide">You need to pick a color.</span>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" @click="confirm">Confirm</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import Events from "../events";
  import validate from "../helpers/ValidateForm";

  export default {
    props: ["categories"],

    data() {
      return {
        mode: "new",
        title: "",
        content: "",
        selectedCategory: "uncategorized",
      }
    },

    computed: {
      formTests()  {
        return [
          {
            container: $("#note-editor__title-holder"),
            conditions: [this.title.trim() !== ""],
            message: $("#note-editor__title-message")
          },
          {
            container: $("#note-editor__content-holder"),
            conditions: [this.content.trim() !== ""],
            message: $("#note-editor__content-message")
          }
        ];
      }
    },

    methods: {
      confirm() {
        if (validate(this.formTests)) {

          Events.emit(this.mode.name, Object.assign(
            {},
            {
              title: this.title.trim(),
              content: this.content.trim(),
              category: {
                key: this.selectedCategory.key,
                color: this.selectedCategory.color
              }
            },
            // If editing an existing note, also pass
            // the note key to the event so it knows
            // which note to modify.
            this.mode.name === "Note__save--create" ? {} :
            {
              key: this.mode.note.key
            }
          ));

          this.title = "";
          this.content = "";
          this.selectedCategory = "uncategorized";
          $("#note-editor").modal("hide");
        }
      }
    },


    created() {
      $("#note-editor").on("shown.bs.modal", function() {
        $("#note-editor__title").focus();
      });

      Events.on("Editor__open--note", () => {
        $("#note-editor").modal("show");
        this.title = "";
        this.content = "";

        this.mode = {
          name: "Note__save--create"
        };

        // Bootstrap-select won't display the options
        // generated by Vue's v-for unless refreshed.
        $("#note-editor__category").selectpicker("refresh");
      });

      Events.on("Note__edit", note => {
        this.title = note.title;
        this.content = note.content;
        this.mode = {
          name: "Note__save--edit",
          note
        };

        $("#note-editor").modal("show");
        $("#note-editor__category").selectpicker("refresh");
      });
    }
  };
</script>